import Header from "./components/Header";
import { Provider} from './components/Clients';
import ToasterWrapper from "./components/ToasterWrapper";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToasterWrapper />
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
